# DATABASE Prod
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://192.168.1.104:5432/solucity-bdd_prod
spring.datasource.username=solucitybdd_prod
spring.datasource.password=solucity