# DATABASE Int
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://192.168.1.102:5432/solucity-bdd_int
spring.datasource.username=solucitybdd_int
spring.datasource.password=solucity