# DATABASE IP int to test before deployment to INT
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://172.31.249.83:5432/solucity-bdd_int
spring.datasource.username=solucitybdd_int
spring.datasource.password=solucity